# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on:
  pull_request:
  push:
  workflow_dispatch:  # Added to allow manual triggering
    inputs:
      release:
        description: 'Create a release (true/false)'
        required: true
        default: 'false'
      tag:
        description: 'Release tag name (e.g., v1.0.0)'
        required: false
        default: ''

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          21,    # Current Java LTS
        ]
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        if: ${{ matrix.java == '21' }} # Only upload artifacts built from latest java
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/

      # Read the current version from gradle.properties for release name
      - name: Extract version from gradle.properties
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.release == 'true' }}
        id: gradle_version
        run: |
          VERSION=$(grep "^version =" gradle.properties | cut -d'=' -f2 | tr -d ' ')
          echo "GRADLE_VERSION=$VERSION" >> $GITHUB_ENV

      # Create Release if manually triggered with release=true
      - name: Create Release
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.release == 'true' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag != '' && github.event.inputs.tag || format('v{0}', env.GRADLE_VERSION) }}
          name: ${{ github.event.inputs.tag != '' && format('Release {0}', github.event.inputs.tag) || format('Release v{0}', env.GRADLE_VERSION) }}
          draft: false
          prerelease: false
          files: |
            build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}